### ISSUE TITLE
QUESTION: I'm not getting any logs & attachment in nested test with multiple assertions  

### ISSUE THREAD

**Issue by mcafeerun** [reportportal/agent-js-jasmine#13]
Hi,

I'm using protractor+jasmine for testing web app. I'm trying to use reportportal jasmine agent to send my results to report portal. But I'm facing some challenges. So, looking for your help to resolve it.

To begin with, I have attached the structure of my spec (instead of my actual test steps, i replaced with dummy assertions) for your reference. 
[jasmineSpec.txt](https://github.com/reportportal/agent-js-jasmine/files/1808221/jasmineSpec.txt)
_Note: jasmineSpec.txt is actually a jasmineSpec.js file._

When I run the above spec, i'm getting the logs/results & picture/attachment in the report portal as expected. Please see the picture below. No issues till this point.

![image](https://user-images.githubusercontent.com/36393899/37363131-87fb0ecc-26cd-11e8-9605-a96abea416de.png)

But when i add my actual test with protractor steps/actions, i see my failed specs are showing only status as failed but i'm not getting the logs or picture/attachment. Not sure if this is anything to do with protractor/jasmine promise not getting resolved. i'm using protractor 5.x.x + jasmine2 framework & jasmine-expect for assertion. 

![image](https://user-images.githubusercontent.com/36393899/37363865-65b17098-26cf-11e8-9ae3-07e31fcc25c6.png)

Note: I use page object model & functions inside the page object to perform any action on the page. So all my expect will looks something similar to this,

```
expect(loginPage.goto()).toBe(true, 'Login page not avilable');
expect(loginPage.login(data.login.username, data.login.password)).toBe(true, 'Login failed'); 
expect(loginPage.loggedIn()).toBe(true, 'Login attempt unsuccessful');
```
Note: When i run the same spec with other reporters (Eg: protractor-beautiful-reporter), i could able to see the failure logs/pictures.

Any help is much appreciated!

**Comment by evjlobanova** [comment]
@mcafeerun  unfortunately we do not have any contributors. So maybe you want to contribute RP? 
Also we have a channel in our Slack chat with  discussion, I suppose it can be useful https://reportportal.slack.com/messages/C9P504QSD

**Comment by mcafeerun** [comment]
@evjlobanova i'm still researching the issue from my end. i will update this ticket if i find something. BTW, slack is blocked in my office network.

Thanks for your reply,  @evjlobanova !

**Comment by mcafeerun** [comment]
When the suite & spec names has some special characters, this is happening. i was able to solve it by refining my spec/suite names.. Thanks @evjlobanova ..!
