### ISSUE TITLE
Unhandled promise rejection if there passed invalid parameters in constructor.

### ISSUE THREAD

**Issue by Niyarlatotep** [reportportal/agent-js-jasmine#14]
If don't pass token, or other parameter, there will be unhandled promise rejection.
Example:
```javascript
const agent = new ReportportalAgent({
    //token: "00000000-0000-0000-0000-000000000000",
    endpoint: "http://your-instance.com:8080/api/v1",
    launch: "LAUNCH_NAME",
    project: "PROJECT_NAME",   
    attachPicturesToLogs: true
});
```
will throw unhandled promise rejection

**Comment by DzmitryHumianiuk** [comment]
@Niyarlatotep coup you plz send us a Pull Request with a fix?

**Comment by Niyarlatotep** [comment]
@DzmitryHumianiuk I'm not so good in node js and so on. This problem occurs if report portal client can't connect report portal server. Agent starts launch (method startLaunch()) and in the launch tries to send some information to api, so if there's no connect restler (module for api requests) throws an error vich not caught.  As I can see from code, these actions perform in class constructor and it's not a good solution at all, constructors shouldn't have side effects so I don't know how to fix this correctly considering this circumstance. I can made some little fix to catch that unhandled error and log it and print to console then just go on but I'm not sure if it's a good decision. Second I think there should be additional in using example that in method getExitPromise() it would be good catch errors.
```
agent.getExitPromise().then(() => {
    console.log('finish work');
},
(e) => {
    console.log('e');
})
```
