### ISSUE TITLE
Add supporting additional parameters to passing in reporter.

### ISSUE THREAD

**Issue by Niyarlatotep** [reportportal/agent-js-jasmine#15]
Would be good to have some way to pass parameters, like tags or description to reporter. For example I 'd like to add testing application build number to launch information, as tags or as description, but there's no such functionality. I've done it by adding to startLaunch method of report-portal-client, after getting launchdata ID:
```
//after geting launchData id from responce
const launchUpdateURL = [url, responce.id, "update"].join("/");
const launchPropertiesUpdate = {description:"", tags: launchData.tags};
helpers.getServerResult(launchUpdateURL, launchPropertiesUpdate, {headers: this.headers}, "PUT")
                            .catch((error)=>{
                                console.dir(error);
                            });
```

Don't sure it's right way. Would be great to have it out of the box.

**Comment by evjlobanova** [comment]
@Niyarlatotep unfortunately, we do not have any jasmine contributors now.   So maybe you want to contribute RP?
Also we have a channel in our Slack chat with discussion, I suppose it can be useful https://reportportal.slack.com/messages/C9P504QSD

**Comment by Niyarlatotep** [comment]
@evjlobanova thank you for response. I'm not sure if I have enough skills for contributing. If I'll make some pull request, with current my fix, is there someone who can have look at it?

**Comment by evjlobanova** [comment]
@Niyarlatotep it will be great! We will appreciate that so much . So you cam try to send  a pull request  and we will find a person for review.
