### ISSUE TITLE
result not getting posted on RP 

### ISSUE THREAD

**Issue by learnappium** [reportportal/agent-js-jasmine#16]
my config.js 
`const ReportportalAgent = require('agent-js-jasmine');
const agent = new ReportportalAgent({
    token: "8736a402-8d39-46ac-99d9-**********",
    endpoint: "http://*********.com",
    launch: "protractortest",
    project: "unified-qa",
    attachPicturesToLogs: false,
    });
exports.config = {
    capabilities: {
        'browserName': 'chrome'
        },
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['rpspec.js'],
    onPrepare: ()=> {       
        jasmine.getEnv().addReporter(agent.getJasmineReporter());
    },
    afterLaunch:() => {
        return agent.getExitPromise();
    }
};`

and my spec file

`describe('second spec', function() { 
    // Test in Jasmine
    it('second specopening home page', function() { 
      browser.get('https://angular.io/')
     expect('true').toBe('true');  
     console.log('--------------------all----------')
    });
  });`

protractor log:
```
`D:\AutomationPOC\proptractor\protractor_rp> protractor .\config.js
(node:5680) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[00:13:07] I/launcher - Running 1 instances of WebDriver
[00:13:07] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
Started
--------------------all----------.
1 spec, 0 failures
Finished in 8.947 seconds

[00:13:18] I/launcher - 0 instance(s) of WebDriver still running
[00:13:18] I/launcher - chrome #01 passed
PS D:\AutomationPOC\proptractor\protractor_rp>`
```
**When i check reportportal project there not launch recorded though spec runs successfully**

protractor version :  Version 5.3.2

**Comment by evjlobanova** [comment]
@yana95  Yana, could you please check this issue?

**Comment by yana95** [comment]
Hello @learnappium, 
Are you sure that you use correct endpoint? Please go in profile page on your instanse of ReportPortal. Open NodeJS tab in CONFIGURATION EXAMPLES and check yor endpoint

**Comment by DzmitryHumianiuk** [comment]
@learnappium still actual?

**Comment by DzmitryHumianiuk** [comment]
closed. since no response.
open new if still actual

**Comment by vaibhavshukl12** [comment]
Hi,@DzmitryHumianiuk @yana95 Hope you are doing well.
I am also facing the same issue please help on this.

**Comment by KatsiarynaTatarynovich** [comment]
Hi, @vaibhavshukl12 Could you please tell me what kind of version RP you use?

**Comment by vaibhavshukl12** [comment]
Hi,@KatsiarynaTatarynovich I am using RP 5.3

**Comment by KatsiarynaTatarynovich** [comment]
@vaibhavshukl12 Could you please run your tests using agent-js-jasmine in debug mode. Just pass `debug: true` in the config. And then please inform us about the result.

**Comment by vaibhavshukl12** [comment]
Hi, @KatsiarynaTatarynovich, I put debug: true in RP conf.
and find the below result.


Running "protractor:singlerun" (protractor) task
Start launch c0m3g4keio8knt
[20:52:16] I/launcher - Running 1 instances of WebDriver
[20:52:16] I/direct - Using ChromeDriver directly...

DevTools listening on ws://127.0.0.1:54037/devtools/browser/ec025129-e986-45bf-bbd7-d8ad83b6e6ee
Spec started
XML report directory cleared!
Start test item c0m3g4keio8sag
Start test item c0m3g4keio8sah
Success start item c0m3g4keio8sag
Start test item c0m3g4keio8sai
Success start item c0m3g4keio8sah
Start test item c0m3g4keio8saj
Success start item c0m3g4keio8sai
Success start item c0m3g4keio8saj
>>>>>>>>Online Shopping Site for Mobiles, Electronics, Furniture, Grocery, Lifestyle, Books & More. Best Offers!

  Flipkart Launch Demo Script
    ✓ Get Page Title
Entity: line 5: parser error : xmlParseEntityRef: no name
    <title>Online Shopping India Mobile, Cameras, Lifestyle & more Online @ Flip
                                                             ^
Save log c0m3g4keio8uvf
Save log c0m3g4keio8v35

Executed 1 of 1 spec SUCCESS in 4 secs.
[20:52:30] I/launcher - 0 instance(s) of WebDriver still running
[20:52:30] I/launcher - chrome #01 passed
Successfully save log c0m3g4keio8uvf
Finish test item c0m3g4keio8sai
Successfully save log c0m3g4keio8v35
Finish test item c0m3g4keio8saj
Success finish item c0m3g4keio8sai
Finish test item c0m3g4keio8sag
Success finish item c0m3g4keio8saj
Finish test item c0m3g4keio8sah
Success finish item c0m3g4keio8sag
Success finish item c0m3g4keio8sah
Finish launch c0m3g4keio8knt
Success finish launch c0m3g4keio8knt

Running "exec:makeReport" (exec) task
Report successfully generated to allure-report

Done.

But still on RP launch is not there
