### ISSUE TITLE
Launch history show "There’re several items with the same UID meaning." 

### ISSUE THREAD

**Issue by minhhoangvn** [reportportal/agent-js-jasmine#20]
My config.js

```
const log4js = require('log4js');
const ReportportalAgent = require('./helper/report-portal-agent');
const agent = new ReportportalAgent({
  token: "5c8c43b8-b56c-4edc-8b0f-1a1450114b54",
  endpoint: "http://localhost:6060/api/v1",
  launch: "demo-protractor",
  project: "demo",
  attachPicturesToLogs: true,
});

const reportPortalAgent = agent.getJasmineReporter();

exports.config = {
  reportClient: agent.client,
  reportAgent: reportPortalAgent,
  framework: 'jasmine',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['spec-1.js', 'spec-2.js'],

  onPrepare: () => {
    jasmine.getEnv().addReporter(reportPortalAgent);
  },

  afterLaunch: () => {
    return agent.getExitPromise().then(() => {
      console.log('finish work');
  })
  }
};
```
After I run multiple tests, ReportPortal can't show the history of the previous launch (it show the message **There’re several items with the same UID meaning.**
![image](https://user-images.githubusercontent.com/17515250/48925319-07334980-eef5-11e8-9dac-9a72c313bcf7.png)

Below is launch history when I run with Java testNG agent:
![image](https://user-images.githubusercontent.com/17515250/48925351-5b3e2e00-eef5-11e8-857b-6eb52feca3dd.png)

**Comment by DzmitryHumianiuk** [comment]
@minhhoangvn that means that there are test cases with exactly the same names.
History line shows test case history based on selection of `uniqueID`
http://reportportal.io/docs/A-test-item%3Euniqueid

It's build on run-time with:
- A project name;
- A launch name;
- Names of all parents;
- All parameters of the item;

Most likely you do not provide any test cases parameters, and name of test case and all parents are equal.
If you test will have at least different names - that it will work
