### ISSUE TITLE
Jasmine not defined Error

### ISSUE THREAD

**Issue by ThatoMolefe** [reportportal/agent-js-jasmine#23]
When I run I add the line: jasmine.getEnv().addReporter(agent.getJasmineReporter()); . I get a an error stating jasmine is not defined.

**Comment by gksangepu** [comment]
can you share your package.json

**Comment by KatsiarynaTatarynovich** [comment]
Hi @ThatoMolefe 
Is this issue still relevant to you?

**Comment by ThatoMolefe** [comment]
Hello Everyone,

No, this issue is now irrelevant

Thank you!
