### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by dubilyer** [reportportal/agent-js-jasmine#26]
After reinstalling agent-gs-jasmine(latest), getting it with dependency reportportal-client: ^5.1.0.

It causes the following issue:

```
> Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at axios.then.catch (C:\Jenkins\Slave\rhel-jenkis01\autouip01\workspace\UI_4615_protractor\SRC\GPP\GPPFrontEnd\WebRoot\node_modules\reportportal-client\lib\rest.js:27:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
 
But in ReportPortal API v. 4.30 (I'm currently using and it's almost impossible for me to upgrade it fast) this parameter should be start_time, but not startTime.

**Comment by KatsiarynaTatarynovich** [comment]
Hi @dubilyer this happens because the agent uses the newest client (v5.5.0) which works with RP v5. I 
suggest you replace the version of "reportportal-client" with 5.1.0 without "^".

**Comment by DiscoElevator** [comment]
You can try to change client's version in your project's `package-lock.json`

**Comment by dubilyer** [comment]
> Hi @dubilyer this happens because the agent uses the newest client (v5.5.0) which works with RP v5. I
> suggest you replace the version of "reportportal-client" with 5.1.0 without "^" in package.json as a temporary solution.

Thanks. Built my private artefact for a while. Thanks for your support. Closing.
