### ISSUE TITLE
Logs sequesnce in RP is broken 

### ISSUE THREAD

**Issue by khrissh** [reportportal/agent-js-jasmine#36]
Hi, I'd like to use RP logger, like PublicReportingAPI.info('My message') and get the log in RP in same sequence as I put the log messages in the code. But log messages are displayed randomly. I use async\await in the specs. For tests use typescript + protractor + jasmine. 

Here are reply on this issue from RP support team in slack:

> Hi, currently there is no way to add the exact sequence of methods by yourself using the capacity of PublicReportingAPI. The order of the logs depends on the start time. Since they are executed one after another, their start time value coincides. In this case, managing the exact log order is difficult. I also want to note that the client works asynchronously, this was done for faster work and it helps limit the impact of the reporter on test execution, therefore it also interferes with organizing the logs.
You can try using workaround with timeout. But it could affect tests.
The time difference is nanoseconds. In the RP we are working with milliseconds, and we do not have the ability to process time in nanoseconds, at the moment

**Comment by DzmitryHumianiuk** [comment]
@khrissh logs are ordered by timestamp in milliseconds.
make sure you have different timestamp for each log you send

**Comment by VeranikaRymzha** [comment]
Hello @khrissh,
JFYI
We plan transferring from milliseconds to microseconds in ReportPortal version 6 so as to provide a higher level of precision and accuracy in the logs timestamps.

**Comment by VeranikaRymzha** [comment]
Hello @khrissh, 
I wanted to let you know that the ReportPortal 24.2 version is now live, along with the improvement you requested. We've added microseconds to the timestamp, providing higher accuracy in the log sequence.

You can find more details about the new features and enhancements in the [release notes](https://reportportal.io/docs/releases/Version24.2/). 
Feel free to try it out and share any feedback you may have.

Have a great day!

**Comment by AmsterGet** [comment]
Hello @khrissh 
For microseconds support make sure to use the agent from version [5.2.0](https://github.com/reportportal/agent-js-jasmine/releases/tag/v5.2.0).
