### ISSUE TITLE
Question: is there a way to pass the self signed certificates? (Error: self signed certificate in certificate chain)

### ISSUE THREAD

**Issue by gksangepu** [reportportal/agent-js-jasmine#43]
Running into an issue 

> "Error: self signed certificate in certificate chain".

is there a way to pass the certificates 
ex: ca: fs.readFileSync("/path/to/CA/file.pem"
Errror:
```
Error connection to server
Error: self signed certificate in certificate chain
    at /path/to/node_modules/reportportal-client/lib/rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Thanks

**Comment by KatsiarynaTatarynovich** [comment]
Hi @gksangepu 
Could you please give me more information.
How do you use it inside of the config or the tests? It would also be nice to see the entire config. 

I also want to mention, that we have just released the new version of the jasmine reporter as a new package @reportportal/agent-js-jasmine: https://www.npmjs.com/package/@reportportal/agent-js-jasmine.
It's fully compatible with ReportPortal version 5.*
Maybe an updated version will help solve your problem

**Comment by evjlobanova** [comment]
Closed due to no answer

**Comment by nklemiata** [comment]
Hi to anyone with the same certificate issue: 

```
Error start launch with tempId bi4rj9dl38lkcgdfqj Error: unable to verify the first certificate
URL: https://<our Report Portal url>/api/v1/<project>/launch
method: POST
    at D:\Repos\hermes-art-ui\node_modules\@reportportal\client-javascript\lib\rest.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Had to add 
```
// REJECT_UNAUTHORIZED = false added to pass SSL issues on reportportal/axios
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';
```
to the top of Protractor.config.js.
It results into a warning, but at least works: 

` Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.`
