### ISSUE TITLE
Attributes and Values are added but still the report has not stopped.

### ISSUE THREAD

**Issue by troyhugs** [reportportal/agent-js-jasmine#51]
Using const ReportportalAgent = require('@reportportal/agent-js-jasmine');

Looks like it is in an infinite loop.
![image](https://user-images.githubusercontent.com/17424203/88833738-5c5a4f00-d1f0-11ea-9591-55999f7f7eb2.png)

![image](https://user-images.githubusercontent.com/17424203/88833778-6da35b80-d1f0-11ea-83c8-c8cacdbab210.png)

**Comment by AmsterGet** [comment]
Hi @troyhugs !
We have released new version 5.0.2 `client-javascript` with a fix that might help!
Please try to completely reinstall the dependencies related to `agent-js-jasmine`.

**Comment by AmsterGet** [comment]
Closed because of no answer from requester.
Feel free to reopen it in case of any other question related to the topic.

**Comment by troyhugs** [comment]
Couldn't find that version... it is still 5.0.0

![image](https://user-images.githubusercontent.com/17424203/97093352-ba1ffb00-1668-11eb-94d3-8c4d4a530112.png)
![image](https://user-images.githubusercontent.com/17424203/97093367-e0de3180-1668-11eb-9a2a-b2d8e8678f42.png)

Hope I am chasing the same you are referring to.

**Comment by AmsterGet** [comment]
I meant the new version of the `client-javascript` package, it is just a subdependency of `agent-js-jasmine`.
To ge the latest version, you need to reinstall the dependencies related to `agent-js-jasmine`.
![image](https://user-images.githubusercontent.com/31861805/97104288-c9806200-16c3-11eb-96d6-896956f3433c.png)
