### ISSUE TITLE
When enabled "attachPicturesToLogs: true" -- error in execution- "Unsupported Media Type"

### ISSUE THREAD

**Issue by troyhugs** [reportportal/agent-js-jasmine#53]
Error: Request failed with status code 415: {"timestamp":1598616176517,"status":415,"error":"Unsupported Media Type","message":"Content type 'multipart/form-data;boundary=7304571891;charset=UTF-8' not supported","path":"/v1/_automation/item/05fba0fd-c74a-4a7a-8a46-474"}
    at /Users/john.v/_QA_Automation/node_modules/@reportportal/client-javascript/lib/rest.js:31:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Request failed with status code 415: {"timestamp":1598616176517,"status":415,"error":"Unsupported Media Type","message":"Content type 'multipart/form-data;boundary=7304571891;charset=UTF-8' not supported","path":"/v1/voyager_automation/item/05fba0fd-c74a-4a7a-8a46-474"}
    at /Users/john.v/_QA_Automation/node_modules/@reportportal/client-javascript/lib/rest.js:31:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by AmsterGet** [comment]
Hi @troyhugs !
My  [comment](https://github.com/reportportal/agent-js-jasmine/issues/51#issuecomment-704925676) may help here too.

**Comment by AmsterGet** [comment]
Closed because of no answer from requester.
Feel free to reopen it in case of any other question related to the topic.
