### ISSUE TITLE
Value is not allowed for field 'status'

### ISSUE THREAD

**Issue by NanoTechnolog3000** [reportportal/agent-js-jasmine#69]
Hi,
I'm having problems using the agent, could anyone help me?

I'm using jasmine-ts and everything works fine in the case if I run all tests suites and specs.
Script to run all specs: `jasmine-ts --config=jasmine.json`

But if I launch jasmine with the 'filter' parameter (to run only specific specs), the next message is thrown several times at the end of the suite:
`Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Value is not allowed for field 'status'.] "}`

Also, all skipped specs in this suite market as 'Failed' on Report Portal

Script to run specs by tag: `jasmine-ts --config=jasmine.json --filter=#smoke`

I report to `Report Portal Build: 5.4.0` via `@reportportal/agent-js-jasmine: 5.0.0`

**Comment by AmsterGet** [comment]
Hello @NanoTechnolog3000 !
Seems like the agent has wrong mapping for `excluded` status to RP statuses.
I'll create the ticket and we will fix this problem.
Thanks for finding.

**Comment by AmsterGet** [comment]
@NanoTechnolog3000 
Oh, I see your PR https://github.com/reportportal/agent-js-jasmine/pull/70
